'''
In Python, logical operators are used to combine or modify the evaluation of boolean expressions.
The three main logical operators are and, or, and not. 
Here's how they work:

1. and - The and operator evaluates to True if both expressions on either side of it are True. 
Otherwise, it evaluates to False.

2. or - The or operator evaluates to True if at least one of the expressions on either side of it is 
True. If both expressions are False, it evaluates to False.

3. not - The not operator negates the expression that follows it. 
So, if the expression is True, not evaluates to False, and if the expression is False, 
not evaluates to True.
'''

x = 5
y = 10
z = 15

# Using 'and' operator
if x < y and y < z:
    print("x is less than y and y is less than z")

# Using 'or' operator
if x > y or y > z:
    print("Either x is greater than y or y is greater than z")

# Using 'not' operator
if not(x == y):
    print("x is not equal to y")

'''
The in and not in operators are used to check if a value exists (or doesn't exist) 
in a given sequence or container in Python.
Here's how they work:

1. in - The in operator checks if a value exists in a given sequence or container. 
It evaluates to True if the value is found, and False otherwise.

2. not in - The not in operator checks if a value does not exist in a given sequence or container. 
It evaluates to True if the value is not found, and False otherwise.
'''
my_list = [1, 2, 3, 4, 5] #List generated by sort

# Using 'in' operator
if 3 in my_list:
    print("3 is in the list")

# Using 'not in' operator
if 6 not in my_list:
    print("6 is not in the list")